[package]
name = "tiny-server"
version = "0.1.0"
authors = ["Ahimasjason <ahimas.jasan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.14.2"
